
Epoch progress:   0%|                                                                                                                                                                                       | 0/3 [03:01<?, ?it/s]
Traceback (most recent call last):
  File "/lustre/home/uceckz0/Project/imae/jobs/../program/imae/main.py", line 97, in <module>
    wandb.log(train_loss, valid_loss)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1838, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1602, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1474, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/uceckz0/miniconda3/envs/imae/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 599, in publish_partial_history
    partial_history.step.num = step
TypeError: 'dict' object cannot be interpreted as an integer